name: Custom Input 
description: Practice workflow to test custom input
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Enter any name
jobs:
  Development:
    name: This joib is for dev
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo  `${{toJSON(github)}}`
        
        
