name: Custom Input 
description: Practice workflow to test custom input
on:
  push:
    branches:
      - main
  workflow_dispatch:
        
jobs:
  Development:
    name: This joib is for dev
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo  `${{toJSON(github)}}`
        
        
